# Generated by Django 2.2.16 on 2022-07-30 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20220731_0229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='Картинка нового поста', upload_to='posts/', verbose_name='Картинка'),
        ),
    ]
